# Generated by Django 5.0.2 on 2025-02-19 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='プラン名')),
                ('description', models.TextField(verbose_name='説明')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='金額')),
                ('currency', models.CharField(default='JPY', max_length=3, verbose_name='通貨')),
                ('interval', models.CharField(choices=[('monthly', '月次'), ('yearly', '年次')], default='yearly', max_length=20, verbose_name='支払い間隔')),
                ('stripe_price_id', models.CharField(max_length=100, verbose_name='Stripe価格ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '支払いプラン',
                'verbose_name_plural': '支払いプラン',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '有効'), ('past_due', '支払い遅延'), ('canceled', 'キャンセル'), ('unpaid', '未払い')], default='active', max_length=20, verbose_name='ステータス')),
                ('stripe_subscription_id', models.CharField(max_length=100, unique=True, verbose_name='Stripeサブスクリプションid')),
                ('current_period_start', models.DateTimeField(verbose_name='現在の期間開始日')),
                ('current_period_end', models.DateTimeField(verbose_name='現在の期間終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='members.member', verbose_name='会員')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.paymentplan', verbose_name='プラン')),
            ],
            options={
                'verbose_name': 'サブスクリプション',
                'verbose_name_plural': 'サブスクリプション',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='金額')),
                ('currency', models.CharField(default='JPY', max_length=3, verbose_name='通貨')),
                ('status', models.CharField(choices=[('pending', '処理中'), ('succeeded', '成功'), ('failed', '失敗'), ('refunded', '返金済み')], default='pending', max_length=20, verbose_name='ステータス')),
                ('stripe_payment_intent_id', models.CharField(max_length=100, unique=True, verbose_name='Stripe支払いインテントID')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支払日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.subscription', verbose_name='サブスクリプション')),
            ],
            options={
                'verbose_name': '支払い',
                'verbose_name_plural': '支払い',
            },
        ),
    ]
