# Generated by Django 5.0.2 on 2025-02-19 11:17

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='協会名')),
                ('type', models.CharField(choices=[('national', '全国協会'), ('regional', '地方協会'), ('prefectural', '都道府県協会')], max_length=20, verbose_name='協会種別')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='協会コード')),
                ('address', models.TextField(verbose_name='住所')),
                ('phone', models.CharField(max_length=15, verbose_name='電話番号')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('website', models.URLField(blank=True, verbose_name='ウェブサイト')),
                ('representative_name', models.CharField(max_length=100, verbose_name='代表者名')),
                ('established_date', models.DateField(verbose_name='設立日')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='associations.association', verbose_name='上位協会')),
            ],
            options={
                'verbose_name': '協会',
                'verbose_name_plural': '協会',
            },
        ),
        migrations.CreateModel(
            name='AssociationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField(verbose_name='入会日')),
                ('is_staff', models.BooleanField(default=False, verbose_name='スタッフフラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='associations.association', verbose_name='協会')),
            ],
            options={
                'verbose_name': '協会会員',
                'verbose_name_plural': '協会会員',
            },
        ),
    ]
