# Generated by Django 5.0.2 on 2025-02-19 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associations', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='members.member', verbose_name='会員'),
        ),
        migrations.AlterUniqueTogether(
            name='associationmember',
            unique_together={('association', 'member')},
        ),
    ]
