# Generated by Django 5.0.2 on 2025-02-19 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', '運営者'), ('instructor', '指導者'), ('member', 'メンバー')], default='member', max_length=20, verbose_name='役割')),
                ('joined_date', models.DateField(verbose_name='入会日')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'クラブ会員',
                'verbose_name_plural': 'クラブ会員',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='クラブ名')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認済み'), ('rejected', '却下'), ('suspended', '停止中')], default='pending', max_length=20, verbose_name='ステータス')),
                ('is_certified', models.BooleanField(default=False, verbose_name='公認クラブ')),
                ('establishment_date', models.DateField(verbose_name='設立日')),
                ('address', models.TextField(verbose_name='住所')),
                ('phone', models.CharField(max_length=15, verbose_name='電話番号')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('website', models.URLField(blank=True, verbose_name='ウェブサイト')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubs', to='associations.association', verbose_name='所属協会')),
            ],
            options={
                'verbose_name': 'クラブ',
                'verbose_name_plural': 'クラブ',
            },
        ),
    ]
