# Generated by Django 5.0.2 on 2025-02-19 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='represented_clubs', to='members.member', verbose_name='代表者'),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clubs.club', verbose_name='クラブ'),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='members.member', verbose_name='会員'),
        ),
        migrations.AlterUniqueTogether(
            name='clubmember',
            unique_together={('club', 'member')},
        ),
    ]
