# Generated by Django 5.0.2 on 2025-02-19 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'アクティブ'), ('inactive', '休会中'), ('withdrawn', '退会')], default='active', max_length=20, verbose_name='ステータス')),
                ('membership_number', models.CharField(max_length=50, unique=True, verbose_name='会員番号')),
                ('first_name', models.CharField(max_length=30, verbose_name='名')),
                ('last_name', models.CharField(max_length=30, verbose_name='姓')),
                ('first_name_kana', models.CharField(max_length=30, verbose_name='名（カナ）')),
                ('last_name_kana', models.CharField(max_length=30, verbose_name='姓（カナ）')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('phone_number', models.CharField(max_length=15, verbose_name='電話番号')),
                ('address', models.TextField(verbose_name='住所')),
                ('emergency_contact_name', models.CharField(max_length=60, verbose_name='緊急連絡先名')),
                ('emergency_contact_phone', models.CharField(max_length=15, verbose_name='緊急連絡先電話番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '会員',
                'verbose_name_plural': '会員',
            },
        ),
    ]
